const fs = require("fs");
const path = require("path");
const PDFDocument = require("pdfkit");

const outputDir = path.join(__dirname, "..", "public", "forms");

// Create output directory if it doesn't exist
if (!fs.existsSync(outputDir)) {
  fs.mkdirSync(outputDir, { recursive: true });
}

function generatePDF(filename, title, contentLines) {
  const doc = new PDFDocument({ margin: 50 });
  const outputPath = path.join(outputDir, filename);
  const stream = fs.createWriteStream(outputPath);
  
  doc.pipe(stream);

  // Draw tricolor ribbon at the top
  doc.rect(50, 45, 170, 5).fill("#FF9933");
  doc.rect(220, 45, 170, 5).fill("#FFFFFF");
  doc.rect(390, 45, 172, 5).fill("#138808");

  // Title
  doc.y = 70;
  doc.fillColor("#0B1F4D")
     .font("Helvetica-Bold")
     .fontSize(16)
     .text(title, { align: "center" });

  doc.fontSize(8)
     .font("Helvetica")
     .fillColor("#666666")
     .text("DIGITAL INDIA CIVIC PORTAL - SIMULATED FORM GUIDE", { align: "center" });

  doc.moveDown(1.5);
  doc.strokeColor("#e2e8f0").lineWidth(1).moveTo(50, doc.y).lineTo(562, doc.y).stroke();
  doc.moveDown(1);

  // Write content
  contentLines.forEach(line => {
    if (line.startsWith("===") || line.startsWith("---")) {
      doc.moveDown(0.5);
      doc.strokeColor("#cbd5e1").lineWidth(0.5).moveTo(50, doc.y).lineTo(562, doc.y).stroke();
      doc.moveDown(0.5);
    } else if (line.startsWith("SECTION") || line.startsWith("INSTRUCTIONS:") || line.includes("GUIDELINES")) {
      doc.moveDown(0.5);
      doc.fillColor("#FF9933")
         .font("Helvetica-Bold")
         .fontSize(10)
         .text(line);
      doc.moveDown(0.5);
    } else if (line.trim().startsWith("[ ]") || line.trim().startsWith("[  ]")) {
      doc.fillColor("#0B1F4D")
         .font("Helvetica")
         .fontSize(10);
      
      // Draw checkbox box
      const currentY = doc.y;
      doc.rect(50, currentY, 10, 10).strokeColor("#0B1F4D").stroke();
      doc.text(line.replace("[ ]", "").replace("[  ]", "").trim(), 70, currentY);
      doc.y = currentY + 18;
    } else {
      doc.fillColor("#0B1F4D")
         .font("Helvetica")
         .fontSize(10)
         .text(line);
    }
  });

  // Footer Disclaimer
  doc.moveDown(2);
  doc.strokeColor("#cbd5e1").lineWidth(0.5).moveTo(50, doc.y).lineTo(562, doc.y).stroke();
  doc.moveDown(0.5);
  doc.fillColor("#94a3b8")
     .font("Helvetica-Oblique")
     .fontSize(8)
     .text("Disclaimer: This document is a simulated guide generated by the Smart Bharat platform. Use official portals like uidai.gov.in, parivahan.gov.in or passportindia.gov.in for official registrations.", { align: "justify" });

  doc.end();
  console.log(`Generated: ${outputPath}`);
}

// 1. Aadhaar PDF Content
generatePDF("aadhaar_update_form.pdf", "AADHAAR DEMOGRAPHIC UPDATE FORM", [
  "INSTRUCTIONS:",
  "1. Please fill the form in BLOCK letters only.",
  "2. Attach valid proof of identity and proof of address.",
  "---",
  "[ ] UPDATE NAME (Name change proof required)",
  "[ ] UPDATE ADDRESS (Proof of address required)",
  "[ ] UPDATE MOBILE NUMBER (OTP verification at Kendra)",
  "[ ] UPDATE DATE OF BIRTH",
  "---",
  "PERSONAL INFORMATION:",
  "Full Name: __________________________________________________________________",
  "Gender:   [ ] Male   [ ] Female   [ ] Transgender",
  "Date of Birth (DD/MM/YYYY): [  /  /    ]",
  "---",
  "ADDRESS DETAILS:",
  "Care of (C/O): _______________________________________________________________",
  "House No / Apt: ____________________ Building Name: __________________________",
  "Street / Road: ____________________ Area / Sector: ___________________________",
  "District / City: __________________ State: ____________________ Pin Code: [______]",
  "---",
  "Mobile Number: [__________]  Email ID: _______________________________________"
]);

// 2. Birth Certificate PDF Content
generatePDF("birth_registration_form.pdf", "FORM 1: BIRTH REGISTRATION REPORT", [
  "INSTRUCTIONS:",
  "1. Register within 21 days of birth at municipal division.",
  "2. Keep discharge certificate from hospital ready.",
  "---",
  "CHILD'S INFORMATION:",
  "Date of Birth (DD/MM/YYYY): [  /  /    ]",
  "Gender:   [ ] Male   [ ] Female",
  "Child's Full Name (if designated): ____________________________________________",
  "---",
  "PLACE OF BIRTH DETAILS:",
  "[ ] Hospital Registration (Name of Hospital): _________________________________",
  "[ ] Home Birth Address: ____________________________________________________",
  "---",
  "PARENT'S DETAILS:",
  "Mother's Name: _________________________ Mother's Aadhaar: [____________]",
  "Father's Name: _________________________ Father's Aadhaar: [____________]",
  "Permanent Address: ___________________________________________________________",
  "---",
  "Signature of Informant: ____________________ Date: [  /  /    ]"
]);

// 3. Medical Certificate PDF Content
generatePDF("medical_certificate_form.pdf", "FORM 1A: MEDICAL CERTIFICATE GUIDE", [
  "INSTRUCTIONS:",
  "1. Required for applicants above 40 years applying for professional driving licenses.",
  "2. Certificate must be certified by a registered medical practitioner.",
  "---",
  "APPLICANT INFORMATION:",
  "Full Name: __________________________________________________________________",
  "Date of Birth: __________________________ Age: ______ Years",
  "Identification Mark: ________________________________________________________",
  "---",
  "MEDICAL QUESTIONNAIRE:",
  "[ ] Does applicant show normal vision parameters?",
  "[ ] Does applicant suffer from color blindness?",
  "[ ] Does applicant show muscle coordination defects?",
  "[ ] Does applicant show signs of epilepsy?",
  "---",
  "DOCTOR'S DECLARATION:",
  "I hereby certify that I have personally examined the applicant and found them FIT / UNFIT.",
  "Doctor's Name: _______________________________________________________________",
  "Medical Council Registration No: __________________ Signature: _______________"
]);

// 4. Passport Checklist PDF Content
generatePDF("passport_checklist_form.pdf", "PASSPORT DOCUMENT CHECKLIST ASSISTANT", [
  "GUIDELINES:",
  "1. Check the items you will carry to your Passport Seva Kendra (PSK) appointment.",
  "2. All copies must be self-attested.",
  "---",
  "PROOF OF ADDRESS (Carry any ONE of these):",
  "[ ] Water Bill or Electricity Bill (Not older than 3 months)",
  "[ ] Active Bank Passbook with applicant's photo",
  "[ ] Aadhaar Card or E-Aadhaar verification copy",
  "[ ] Registered Rent Agreement",
  "---",
  "PROOF OF DATE OF BIRTH (Carry any ONE of these):",
  "[ ] Birth Certificate issued by municipal authority",
  "[ ] Matriculation (Class 10) Board Certificate",
  "[ ] PAN Card issued by Income Tax Department",
  "[ ] Driving License",
  "---",
  "NON-ECR PROOF (If applicant qualified Class 10+):",
  "[ ] Class 10 Passing Certificate showing Non-ECR status"
]);
